name: Run vote script every 2 hours

on:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches:
      - main

jobs:
  run-vote-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Get Chrome version
        id: get_chrome_version
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1-3)
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

      - name: Get ChromeDriver version
        id: get_chromedriver_version
        run: |
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION} || echo "Not Found")
          if [ "$CHROMEDRIVER_VERSION" == "Not Found" ]; then
            echo "Error: ChromeDriver version not found for Chrome version $CHROME_VERSION" >&2
            exit 1
          fi
          echo "CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION" >> $GITHUB_ENV

      - name: Install ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/${{ env.CHROMEDRIVER_VERSION }}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run vote script
        run: xvfb-run -a python vote.py
